---      
   - name: install php-fpm 
     action: apt name=php5-fpm state=installed    

   - name: php install needed modules
     action: apt name={{ item }} state=installed    
     with_items:
        - php5-common
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-mysql
        - php5-memcache
        - php-apc

   - name: fpm config
     action: template src=www.conf dest=/etc/php5/fpm/pool.d/www.conf

   - name: php.ini settings
     action: ini_file dest=/etc/php5/fpm/php.ini section=PHP option={{ item.option }} value={{ item.value }}
     with_items:
     - { option: 'memory_limit',        value: '128M' }
     - { option: 'post_max_size',       value: '48M'  }
     - { option: 'upload_max_filesize', value: '32M'  }


   - name: Start php5-fpm
     action: service name=php5-fpm state=started
