--- 

- name: install memcached
  action: apt name=memcached state=installed

- name: write memcached.conf
  action: template src=memcached.conf.j2 dest=/etc/memcached.conf mode=0644
  notify:
  - restart memcached



- name: service memcached
  action: service name=memcached state=started 

